apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-clusterissuer-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-clusterissuer-viewer
subjects:
- kind: ServiceAccount
  name: mikrotik-cert-uploader
  namespace: default
