apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"secret-reader","namespace":"default"},"rules":[{"apiGroups":[""],"resources":["secrets"],"verbs":["get","list"]}]}
  creationTimestamp: "2025-10-16T14:21:21Z"
  name: secret-reader
  namespace: default
  resourceVersion: "3179768"
  uid: 602c4bc0-9951-4cc1-b52d-612053a0fbcc
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
