name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write  # Required for trusted publishing to PyPI

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Extract version from tag
      id: get_version
      run: |
        # Extract version from tag (e.g., v1.0.0 -> 1.0.0)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"

    - name: Update version in pyproject.toml
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
        echo "Updated pyproject.toml with version $VERSION"

    - name: Update version in __init__.py
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        sed -i "s/^__version__ = .*/__version__ = \"$VERSION\"/" src/__init__.py
        echo "Updated __init__.py with version $VERSION"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
